name: Prepare Beta Release

on:
  pull_request:
    types: [labeled]

jobs:
  bumpPrepatch:
    if: ${{ github.event.label.name == 'release patch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-verison }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Bump version to next prepatch
        run: npm run bump-prepatch
